name: lua_lint

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install luarocks
      run: |
        sudo apt-get install luarocks -qyy

    - name: Install luacheck
      run: |
        sudo luarocks install luacheck

    - name: Run checks
      run: |
        luacheck ./
